Install Pandas

pip install pandas

Import Pandas

In [9]:
import pandas as pd

Read the data

File Handling

```
try:
  data = pd.read_csv('path_of_file')
except FileNotFoundError as e:
  print("File not found:", e)
```

In [ ]:
data = pd.read_csv('../dataset/titanic.csv')
data

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,0,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,0,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,1309,0,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

Display the top 5 records in the data

In [ ]:
data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [ ]:
data.head(15)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
5,897,0,3,"Svensson, Mr. Johan Cervin",male,14.0,0,0,7538,9.2250,NaN,S
6,898,1,3,"Connolly, Miss. Kate",female,30.0,0,0,330972,7.6292,NaN,Q
7,899,0,2,"Caldwell, Mr. Albert Francis",male,26.0,1,1,248738,29.0000,NaN,S
8,900,1,3,"Abrahim, Mrs. Joseph (Sophie Halaut Easu)",female,18.0,0,0,2657,7.2292,NaN,C
9,901,0,3,"Davies, Mr. John Samuel",male,21.0,2,0,A/4 48871,24.1500,NaN,S
10,902,0,3,"Ilieff, Mr. Ylio",male,NaN,0,0,349220,7.8958,NaN,S
11,903,0,1,"Jones, Mr. Charles Cresson",male,46.0,0,0,694,26.0000,NaN,S
12,904,1,1,"Snyder, Mrs. John Pillsbury (Nelle Stevenson)",female,23.0,1,0,21228,82.2667,B45,S
13,905,0,2,"Howard, Mr. Benjamin",male,63.0,1,0,24065,26.0000,NaN,S
14,906,1,1,"Chaffee, Mrs. Herbert Fuller (Carrie Constance...",female,47.0,1,0,W.E.P. 5734,61.1750,E31,S

Display the last few records in the dataframe

In [ ]:
data.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
413,1305,0,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,0,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,1309,0,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

In [ ]:
data.tail(15)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
403,1295,0,1,"Carrau, Mr. Jose Pedro",male,17.0,0,0,113059,47.1000,NaN,S
404,1296,0,1,"Frauenthal, Mr. Isaac Gerald",male,43.0,1,0,17765,27.7208,D40,C
405,1297,0,2,"Nourney, Mr. Alfred (Baron von Drachstedt"")""",male,20.0,0,0,SC/PARIS 2166,13.8625,D38,C
406,1298,0,2,"Ware, Mr. William Jeffery",male,23.0,1,0,28666,10.5000,NaN,S
407,1299,0,1,"Widener, Mr. George Dunton",male,50.0,1,1,113503,211.5000,C80,C
408,1300,1,3,"Riordan, Miss. Johanna Hannah""""",female,NaN,0,0,334915,7.7208,NaN,Q
409,1301,1,3,"Peacock, Miss. Treasteall",female,3.0,1,1,SOTON/O.Q. 3101315,13.7750,NaN,S
410,1302,1,3,"Naughton, Miss. Hannah",female,NaN,0,0,365237,7.7500,NaN,Q
411,1303,1,1,"Minahan, Mrs. William Edward (Lillian E Thorpe)",female,37.0,1,0,19928,90.0000,C78,Q
412,1304,1,3,"Henriksson, Miss. Jenny Lovisa",female,28.0,0,0,347086,7.7750,NaN,S
413,1305,0,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,0,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,1309,0,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

Data Structure: Dataframe

In [ ]:
type(data)

pandas.core.frame.DataFrame

In [ ]:
type(data['PassengerId'])

pandas.core.series.Series

Series in Depth: It's a one dimensional array-like structure in Pandas that can hold a sequence of value of any data type. Each value in a Series is linked with a associated label, known as the index. You can also customize the index labels in the series.

Create a series from scalar value with the custom index

In [ ]:
series_scalar = pd.Series(10, index=['a', 'b', 'c', 'd', 'e', 'f'])
print(series_scalar)

a    10
b    10
c    10
d    10
e    10
f    10
dtype: int64

In [ ]:
series_scalar['e']

np.int64(10)

In [ ]:
data = [10, 20, 30, 40, 50, 60, 70]
series_list = pd.Series(data)
print(series_list)

0    10
1    20
2    30
3    40
4    50
5    60
6    70
dtype: int64

In [ ]:
import numpy as np
data_array = np.array([10, 20, 30, 40, 50, 60])
series_custom_array = pd.Series(data_array, index=['a', 'b', 'c', 'd', 'e', 'f'])
series_custom_array

a    10
b    20
c    30
d    40
e    50
f    60
dtype: int64

In [ ]:
data_dict = {'a': 10, 'b': 20, 'c': 30, 'd': 40, 'e': 50}
series_dict = pd.Series(data_dict)
series_dict

a    10
b    20
c    30
d    40
e    50
dtype: int64

Slicing

In [ ]:
series_dict[1:4]

b    20
c    30
d    40
dtype: int64

In [ ]:
series_dict['b':'d']

b    20
c    30
d    40
dtype: int64

Attributes in Series Data Structure

In [ ]:
data = ['New Delhi', 'Washington', 'London', 'Paris']
index = ['India', 'USA', 'UK', 'France']

series_capital_country = pd.Series(data, index=index)
print(series_capital_country)

India      New Delhi
USA       Washington
UK            London
France         Paris
dtype: object

In [ ]:
print("Index of the series_capital_country")
print(series_capital_country.index)

Index of the series_capital_country
Index(['India', 'USA', 'UK', 'France'], dtype='object')

In [ ]:
print(type(series_capital_country.index))

<class 'pandas.core.indexes.base.Index'>

In [ ]:
print("Values of the series_capital_country")
print(series_capital_country.values)

Values of the series_capital_country
['New Delhi' 'Washington' 'London' 'Paris']

Dtype is data type of each element in that type of data structure

In [ ]:
print("Data type of the series_capital_country")
print(series_capital_country.dtype)

Data type of the series_capital_country
object

In [ ]:
print("Shape of the series_capital_country")
print(series_capital_country.shape)

Shape of the series_capital_country
(4,)

In [ ]:
print("Size of the series_capital_country")
print(series_capital_country.size)

Size of the series_capital_country
4

In [ ]:
print("Is series_capital_country empty?")
print(series_capital_country.empty)

Is series_capital_country empty?
False

In [ ]:
print("Is series_capital_country contains NaN?")
print(series_capital_country.hasnans)

Is series_capital_country contains NaN?
False

In [ ]:
print("Is series_capital_country contains unique elements?")
print(series_capital_country.is_unique)

Is series_capital_country contains unique elements?
True

In [ ]:
print("Dimensions of the series_capital_country")
print(series_capital_country.ndim)

Dimensions of the series_capital_country
1

In [ ]:
empty_series = pd.Series()
print(empty_series)

Series([], dtype: object)

In [ ]:
print("Is empty_series empty?")
print(empty_series.empty)

Is empty_series empty?
True

Methods in Series Data Structure

In [ ]:
series_capital_country.head(2)

India     New Delhi
USA      Washington
dtype: object

In [ ]:
series_capital_country.tail(2)

UK        London
France     Paris
dtype: object

In [ ]:
marks = [85, 60, 74, 66, 89, 91]
students = ['Ram', 'Priya', 'Rashmi', 'Vidushi', 'Mohit', 'Karan']

series_students = pd.Series(marks, index=students)
print(series_students)

Ram        85
Priya      60
Rashmi     74
Vidushi    66
Mohit      89
Karan      91
dtype: int64

To get the descriptive statistics of the given data

In [ ]:
series_students.describe()

count     6.000000
mean     77.500000
std      12.817956
min      60.000000
25%      68.000000
50%      79.500000
75%      88.000000
max      91.000000
dtype: float64

value_counts()

In [ ]:
series_students.value_counts()

85    1
60    1
74    1
66    1
89    1
91    1
Name: count, dtype: int64

sort_values()

In [ ]:
series_students.sort_values()

Priya      60
Vidushi    66
Rashmi     74
Ram        85
Mohit      89
Karan      91
dtype: int64

drop()

```
series_students = series_students.drop('Karan')
series_students
```

In [ ]:
series_students.drop('Karan', inplace=True)

In [ ]:
series_students

Ram        85
Priya      60
Rashmi     74
Vidushi    66
Mohit      89
dtype: int64

isnull() -> Detect the missing values

In [ ]:
print(series_students.isnull())

Ram        False
Priya      False
Rashmi     False
Vidushi    False
Mohit      False
dtype: bool

In [ ]:
print(series_students.isnull().sum())

0

Task: Mathematical Operations on Series

1. Addition of two Series

2. Subtraction of two Series

3. Multiplication of two Series

4. Division of two Series

In [ ]:
series_students['Karan'] = 91
series_students

Ram        85
Priya      60
Rashmi     74
Vidushi    66
Mohit      89
Karan      91
dtype: int64

Task: Simulate the same approach for a dataframe and you need to cover all the attributes and methods for the dataframe

Import all the required libraries

In [ ]:
import pandas as pd
import numpy as np

Read the data

In [ ]:
data = pd.read_excel('../dataset/customers.xlsx')
data.head()

ImportError: Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl.

Summary of the dataframe information

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             1000 non-null   int64
 1   first_name     1000 non-null   object
 2   last_name      1000 non-null   object
 3   email          878 non-null    object
 4   gender         957 non-null    object
 5   street_num     738 non-null    float64
 6   street_name    963 non-null    object
 7   street_suffix  963 non-null    object
 8   city           921 non-null    object
 9   state          920 non-null    object
 10  postcode       843 non-null    float64
dtypes: float64(2), int64(1), object(8)
memory usage: 86.1+ KB

Add a new column named as 'Country' and the value inside that is 'USA' in the above dataframe.

In [ ]:
data['Country'] = 'USA'

In [ ]:
data.head()

,id,first_name,last_name,email,gender,street_num,street_name,street_suffix,city,state,postcode,Country
0,1,Romain,Southcott,rsouthcott0@clickbank.net,Male,1.0,Trailsway,Road,San Diego,California,92127.0,USA
1,2,Cosimo,Molyneaux,cmolyneaux1@wiley.com,Male,NaN,NaN,NaN,El Paso,Texas,NaN,USA
2,3,Bambi,Westrip,bwestrip2@symantec.com,Female,4057.0,Arkansas,Circle,San Antonio,Texas,78220.0,USA
3,4,Roarke,Pankettman,rpankettman3@wiley.com,Male,74.0,Debs,Point,Memphis,Tennessee,38150.0,USA
4,5,Mikaela,Althorpe,malthorpe4@51.la,NaN,NaN,2nd,Drive,NaN,NaN,83732.0,USA

Task 1: I want to place the 'country' column after the 'city' column.

In [ ]:
membership_status = ['Gold', 'Silver', 'Bronze']
data['membership_status'] = membership_status
data.head()

ValueError: Length of values (3) does not match length of index (1000)

Create a new column 'full_name' which is composed of first_name and the last_name.

In [ ]:
data['full_name'] = data['first_name'] + ' ' + data['last_name']
data.head()

,id,first_name,last_name,email,gender,street_num,street_name,street_suffix,city,state,postcode,Country,full_name
0,1,Romain,Southcott,rsouthcott0@clickbank.net,Male,1.0,Trailsway,Road,San Diego,California,92127.0,USA,Romain Southcott
1,2,Cosimo,Molyneaux,cmolyneaux1@wiley.com,Male,NaN,NaN,NaN,El Paso,Texas,NaN,USA,Cosimo Molyneaux
2,3,Bambi,Westrip,bwestrip2@symantec.com,Female,4057.0,Arkansas,Circle,San Antonio,Texas,78220.0,USA,Bambi Westrip
3,4,Roarke,Pankettman,rpankettman3@wiley.com,Male,74.0,Debs,Point,Memphis,Tennessee,38150.0,USA,Roarke Pankettman
4,5,Mikaela,Althorpe,malthorpe4@51.la,NaN,NaN,2nd,Drive,NaN,NaN,83732.0,USA,Mikaela Althorpe

Access the rows in a given dataframe: .loc() vs .iloc()

In [ ]:
dataframe_demo = {
    'Name': ['Akash', 'Amir', 'Abhishek', 'Nehal', 'Abhijeet'],
    'Age': [23, 34, 25, 27, 36],
    'City': ['Delhi', 'Bengaluru', 'Haryana', 'Noida', 'Pune']
}

dataframe_demo = pd.DataFrame(dataframe_demo, index=['a', 'b', 'c', 'd', 'e'])
dataframe_demo

       Name  Age       City
a     Akash   23      Delhi
b      Amir   34  Bengaluru
c  Abhishek   25    Haryana
d     Nehal   27      Noida
e  Abhijeet   36       Pune

In [ ]:
dataframe_demo.loc['b']

Name         Amir
Age            34
City    Bengaluru
Name: b, dtype: object

In [ ]:
dataframe_demo.loc['b':'d']

       Name  Age       City
b      Amir   34  Bengaluru
c  Abhishek   25    Haryana
d     Nehal   27      Noida

In [ ]:
dataframe_demo.iloc[1]

Name         Amir
Age            34
City    Bengaluru
Name: b, dtype: object

In [ ]:
dataframe_demo.iloc[1:4]

       Name  Age       City
b      Amir   34  Bengaluru
c  Abhishek   25    Haryana
d     Nehal   27      Noida

In [ ]:
dataframe_demo_v1 = {
    'Name': ['Akash', 'Amir', 'Abhishek', 'Nehal', 'Abhijeet'],
    'Age': [23, 34, 25, 27, 36],
    'City': ['Delhi', 'Bengaluru', 'Haryana', 'Noida', 'Pune']
}

dataframe_demo_v1 = pd.DataFrame(dataframe_demo_v1)
dataframe_demo_v1

       Name  Age       City
0     Akash   23      Delhi
1      Amir   34  Bengaluru
2  Abhishek   25    Haryana
3     Nehal   27      Noida
4  Abhijeet   36       Pune

In [ ]:
dataframe_demo_v1.loc[0]

Name    Akash
Age        23
City    Delhi
Name: 0, dtype: object

In [ ]:
dataframe_demo_v1.iloc[0]

Name    Akash
Age        23
City    Delhi
Name: 0, dtype: object

In [ ]:
data.head()

,id,first_name,last_name,email,gender,street_num,street_name,street_suffix,city,state,postcode,Country,full_name
0,1,Romain,Southcott,rsouthcott0@clickbank.net,Male,1.0,Trailsway,Road,San Diego,California,92127.0,USA,Romain Southcott
1,2,Cosimo,Molyneaux,cmolyneaux1@wiley.com,Male,NaN,NaN,NaN,El Paso,Texas,NaN,USA,Cosimo Molyneaux
2,3,Bambi,Westrip,bwestrip2@symantec.com,Female,4057.0,Arkansas,Circle,San Antonio,Texas,78220.0,USA,Bambi Westrip
3,4,Roarke,Pankettman,rpankettman3@wiley.com,Male,74.0,Debs,Point,Memphis,Tennessee,38150.0,USA,Roarke Pankettman
4,5,Mikaela,Althorpe,malthorpe4@51.la,NaN,NaN,2nd,Drive,NaN,NaN,83732.0,USA,Mikaela Althorpe

In [ ]:
data.shape

(1000, 13)

Access the details of the id's of the customers from 500 to 504.

In [ ]:
data.loc[500:504]

,id,first_name,last_name,email,gender,street_num,street_name,street_suffix,city,state,postcode,Country,full_name
500,501,Elliot,Polycote,epolycotedw@infoseek.co.jp,Male,NaN,Prentice,Drive,Hartford,Connecticut,NaN,USA,Elliot Polycote
501,502,Shirline,Halpin,shalpindx@moonfruit.com,NaN,76640.0,Buell,Circle,Dallas,Texas,75216.0,USA,Shirline Halpin
502,503,Darcy,Cruddace,NaN,NaN,NaN,Ridgeview,Court,Utica,New York,13505.0,USA,Darcy Cruddace
503,504,Toiboid,Bentzen,tbentzendz@freewebs.com,Male,913.0,2nd,Trail,White Plains,New York,10606.0,USA,Toiboid Bentzen
504,505,Paxon,Corris,pcorrise0@behance.net,Male,8362.0,Eliot,Way,Des Moines,Iowa,50362.0,USA,Paxon Corris

In [ ]:
data.iloc[500:504]

,id,first_name,last_name,email,gender,street_num,street_name,street_suffix,city,state,postcode,Country,full_name
500,501,Elliot,Polycote,epolycotedw@infoseek.co.jp,Male,NaN,Prentice,Drive,Hartford,Connecticut,NaN,USA,Elliot Polycote
501,502,Shirline,Halpin,shalpindx@moonfruit.com,NaN,76640.0,Buell,Circle,Dallas,Texas,75216.0,USA,Shirline Halpin
502,503,Darcy,Cruddace,NaN,NaN,NaN,Ridgeview,Court,Utica,New York,13505.0,USA,Darcy Cruddace
503,504,Toiboid,Bentzen,tbentzendz@freewebs.com,Male,913.0,2nd,Trail,White Plains,New York,10606.0,USA,Toiboid Bentzen

In [ ]:
data[(data['id'] >= 500) & (data['id'] <= 504)]

,id,first_name,last_name,email,gender,street_num,street_name,street_suffix,city,state,postcode,Country,full_name
499,500,Carolann,Balcock,cbalcockdv@alexa.com,Female,NaN,Stone Corner,Pass,El Paso,Texas,79916.0,USA,Carolann Balcock
500,501,Elliot,Polycote,epolycotedw@infoseek.co.jp,Male,NaN,Prentice,Drive,Hartford,Connecticut,NaN,USA,Elliot Polycote
501,502,Shirline,Halpin,shalpindx@moonfruit.com,NaN,76640.0,Buell,Circle,Dallas,Texas,75216.0,USA,Shirline Halpin
502,503,Darcy,Cruddace,NaN,NaN,NaN,Ridgeview,Court,Utica,New York,13505.0,USA,Darcy Cruddace
503,504,Toiboid,Bentzen,tbentzendz@freewebs.com,Male,913.0,2nd,Trail,White Plains,New York,10606.0,USA,Toiboid Bentzen

In [ ]:
data[500:504]

,id,first_name,last_name,email,gender,street_num,street_name,street_suffix,city,state,postcode,Country,full_name
500,501,Elliot,Polycote,epolycotedw@infoseek.co.jp,Male,NaN,Prentice,Drive,Hartford,Connecticut,NaN,USA,Elliot Polycote
501,502,Shirline,Halpin,shalpindx@moonfruit.com,NaN,76640.0,Buell,Circle,Dallas,Texas,75216.0,USA,Shirline Halpin
502,503,Darcy,Cruddace,NaN,NaN,NaN,Ridgeview,Court,Utica,New York,13505.0,USA,Darcy Cruddace
503,504,Toiboid,Bentzen,tbentzendz@freewebs.com,Male,913.0,2nd,Trail,White Plains,New York,10606.0,USA,Toiboid Bentzen

In [ ]:
data.drop(columns=['Country'], inplace=True)
data.head()

,id,first_name,last_name,email,gender,street_num,street_name,street_suffix,city,state,postcode,full_name
0,1,Romain,Southcott,rsouthcott0@clickbank.net,Male,1.0,Trailsway,Road,San Diego,California,92127.0,Romain Southcott
1,2,Cosimo,Molyneaux,cmolyneaux1@wiley.com,Male,NaN,NaN,NaN,El Paso,Texas,NaN,Cosimo Molyneaux
2,3,Bambi,Westrip,bwestrip2@symantec.com,Female,4057.0,Arkansas,Circle,San Antonio,Texas,78220.0,Bambi Westrip
3,4,Roarke,Pankettman,rpankettman3@wiley.com,Male,74.0,Debs,Point,Memphis,Tennessee,38150.0,Roarke Pankettman
4,5,Mikaela,Althorpe,malthorpe4@51.la,NaN,NaN,2nd,Drive,NaN,NaN,83732.0,Mikaela Althorpe

Rename the row index with the custom index.

'0' - 'firstCustomer'

'1' - 'secondCustomer'

In [ ]:
rename_dict = {
    0: 'firstCustomer',
    1: 'secondCustomer'
}

data.rename(index=rename_dict, inplace=True)
data.head()

,id,first_name,last_name,email,gender,street_num,street_name,street_suffix,city,state,postcode,full_name
firstCustomer,1,Romain,Southcott,rsouthcott0@clickbank.net,Male,1.0,Trailsway,Road,San Diego,California,92127.0,Romain Southcott
secondCustomer,2,Cosimo,Molyneaux,cmolyneaux1@wiley.com,Male,NaN,NaN,NaN,El Paso,Texas,NaN,Cosimo Molyneaux
2,3,Bambi,Westrip,bwestrip2@symantec.com,Female,4057.0,Arkansas,Circle,San Antonio,Texas,78220.0,Bambi Westrip
3,4,Roarke,Pankettman,rpankettman3@wiley.com,Male,74.0,Debs,Point,Memphis,Tennessee,38150.0,Roarke Pankettman
4,5,Mikaela,Althorpe,malthorpe4@51.la,NaN,NaN,2nd,Drive,NaN,NaN,83732.0,Mikaela Althorpe

Task 2: Can you rename the columns of street_num with the street_number and street_name with the street_address.

For non customised index iloc = loc else they are different.

In [ ]:
data.loc['firstCustomer':'secondCustomer']

,id,first_name,last_name,email,gender,street_num,street_name,street_suffix,city,state,postcode,full_name
firstCustomer,1,Romain,Southcott,rsouthcott0@clickbank.net,Male,1.0,Trailsway,Road,San Diego,California,92127.0,Romain Southcott
secondCustomer,2,Cosimo,Molyneaux,cmolyneaux1@wiley.com,Male,NaN,NaN,NaN,El Paso,Texas,NaN,Cosimo Molyneaux

In [ ]:
data.iloc[0:2]

,id,first_name,last_name,email,gender,street_num,street_name,street_suffix,city,state,postcode,full_name
firstCustomer,1,Romain,Southcott,rsouthcott0@clickbank.net,Male,1.0,Trailsway,Road,San Diego,California,92127.0,Romain Southcott
secondCustomer,2,Cosimo,Molyneaux,cmolyneaux1@wiley.com,Male,NaN,NaN,NaN,El Paso,Texas,NaN,Cosimo Molyneaux

Finding the unique values

In [ ]:
unique_gender = data['gender'].unique()
print(unique_gender)

['Male' 'Female' nan]

Count of the unique values in the given column in a dataframe.

Note: It will only return the non-null values as the count.

In [ ]:
count_unique_gender = data['gender'].nunique()
print(count_unique_gender)

2

In [ ]:
data['gender'].value_counts()

gender
Male      485
Female    472
Name: count, dtype: int64

In [ ]:
data.dtypes

id                 int64
first_name        object
last_name         object
email             object
gender            object
street_num       float64
street_name       object
street_suffix     object
city              object
state             object
postcode         float64
full_name         object
dtype: object

In [ ]:
data_purchases = pd.read_excel('../dataset/purchases.xlsx')
data_purchases.head()

,Unnamed: 0,id,purch_date,customer_num,product_num,amount,paid
0,0,1,2019-01-03 00:00:00,823,27,12,$568.92
1,1,2,2019-01-03 00:00:00,606,28,14,$395.36
2,2,3,2019-01-03 00:00:00,955,9,17,$510.17
3,3,4,2019-01-03 00:00:00,577,19,3,$68.49
4,4,5,2019-01-03 00:00:00,429,8,18,$759.42

In [ ]:
data_purchases.dtypes

Unnamed: 0       int64
id               int64
purch_date      object
customer_num     int64
product_num      int64
amount           int64
paid            object
dtype: object

In [ ]:
data_purchases.drop(columns=['Unnamed: 0'], inplace=True)
data_purchases.head()

   id           purch_date  customer_num  product_num  amount     paid
0   1  2019-01-03 00:00:00           823           27      12  $568.92
1   2  2019-01-03 00:00:00           606           28      14  $395.36
2   3  2019-01-03 00:00:00           955            9      17  $510.17
3   4  2019-01-03 00:00:00           577           19       3   $68.49
4   5  2019-01-03 00:00:00           429            8      18  $759.42

Handle the data types of the column in an appropriate manner.

purch_data -> datetime

In [ ]:
data_purchases['purch_date'] = pd.to_datetime(data_purchases['purch_date'])
data_purchases.dtypes

id                       int64
purch_date      datetime64[ns]
customer_num             int64
product_num              int64
amount                   int64
paid                    object
dtype: object

id -> object

In [ ]:
data_purchases['id'] = data_purchases['id'].astype(object)
data_purchases.dtypes

id                      object
purch_date      datetime64[ns]
customer_num             int64
product_num              int64
amount                   int64
paid                    object
dtype: object

paid -> float

In [ ]:
## paid -> data preprocess and then only we can do the type-conversion

## the below code will simply remove the $ and , from the paid column using a regular expression
data_purchases['paid'] = data_purchases['paid'].str.replace('[\$,]', '', regex=True)
data_purchases.head()

  id purch_date  customer_num  product_num  amount    paid
0  1 2019-01-03           823           27      12  568.92
1  2 2019-01-03           606           28      14  395.36
2  3 2019-01-03           955            9      17  510.17
3  4 2019-01-03           577           19       3   68.49
4  5 2019-01-03           429            8      18  759.42

In [ ]:
data_purchases.dtypes

id                      object
purch_date      datetime64[ns]
customer_num             int64
product_num              int64
amount                   int64
paid                    object
dtype: object

In [ ]:
data_purchases['paid'] = data_purchases['paid'].astype(float)
data_purchases.dtypes

id                      object
purch_date      datetime64[ns]
customer_num             int64
product_num              int64
amount                   int64
paid                   float64
dtype: object

In [8]:
data_products = pd.read_excel('../dataset/products.xlsx')
data_products.head()

ImportError: Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl.

In [ ]:
data_products.dtypes

Unnamed: 0     int64
id             int64
product       object
cost          object
company       object
dtype: object

In [ ]:
data_products.drop(columns=['Unnamed: 0'], inplace=True)

In [ ]:
data_products.dtypes

id          int64
product    object
cost       object
company    object
dtype: object

In [ ]:
data_products['cost'] = data_products['cost'].str.replace('[\$, ]', '', regex=True).astype(float)
data_products.dtypes

id           int64
product     object
cost       float64
company     object
dtype: object

In [ ]:
data_products['id'] = data_products['id'].astype(object)
data_products.dtypes

id          object
product     object
cost       float64
company     object
dtype: object

In [ ]:
data_purchases.shape

(6000, 6)

In [ ]:
data_products.shape

(60, 4)

In [ ]:
data.shape

(1000, 12)

SQL Union

pd.concat -> to manipulation and combine multiple dataframes in pandas.

In [ ]:
combined_df = pd.concat([data, data_purchases, data_products]) ## axis = 0[default] row-wise concatenation, axis = 1 -> column wise concatenation
combined_df

,id,first_name,last_name,email,gender,street_num,street_name,street_suffix,city,state,postcode,full_name,purch_date,customer_num,product_num,amount,paid,product,cost,company
firstCustomer,1,Romain,Southcott,rsouthcott0@clickbank.net,Male,1.0,Trailsway,Road,San Diego,California,92127.0,Romain Southcott,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
secondCustomer,2,Cosimo,Molyneaux,cmolyneaux1@wiley.com,Male,NaN,NaN,NaN,El Paso,Texas,NaN,Cosimo Molyneaux,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,Bambi,Westrip,bwestrip2@symantec.com,Female,4057.0,Arkansas,Circle,San Antonio,Texas,78220.0,Bambi Westrip,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,Roarke,Pankettman,rpankettman3@wiley.com,Male,74.0,Debs,Point,Memphis,Tennessee,38150.0,Roarke Pankettman,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,Mikaela,Althorpe,malthorpe4@51.la,NaN,NaN,2nd,Drive,NaN,NaN,83732.0,Mikaela Althorpe,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55,56,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,Peach - Fresh,20.53,Zazio
56,57,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,Muffin Hinge - 211n,68.63,Fanoodle
57,58,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,Bar Bran Honey Nut,73.05,Yakijo
58,59,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,"Nut - Almond, Blanched, Whole",74.28,Eazzy
59,60,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,Table Cloth 90x90 Colour,41.22,Quinu

SQL Joins => Inner, Left, Right, Outer

pd.merge

In [ ]:
data.head()

,id,first_name,last_name,email,gender,street_num,street_name,street_suffix,city,state,postcode,full_name
firstCustomer,1,Romain,Southcott,rsouthcott0@clickbank.net,Male,1.0,Trailsway,Road,San Diego,California,92127.0,Romain Southcott
secondCustomer,2,Cosimo,Molyneaux,cmolyneaux1@wiley.com,Male,NaN,NaN,NaN,El Paso,Texas,NaN,Cosimo Molyneaux
2,3,Bambi,Westrip,bwestrip2@symantec.com,Female,4057.0,Arkansas,Circle,San Antonio,Texas,78220.0,Bambi Westrip
3,4,Roarke,Pankettman,rpankettman3@wiley.com,Male,74.0,Debs,Point,Memphis,Tennessee,38150.0,Roarke Pankettman
4,5,Mikaela,Althorpe,malthorpe4@51.la,NaN,NaN,2nd,Drive,NaN,NaN,83732.0,Mikaela Althorpe

In [ ]:
data_purchases.head()

  id purch_date  customer_num  product_num  amount    paid
0  1 2019-01-03           823           27      12  568.92
1  2 2019-01-03           606           28      14  395.36
2  3 2019-01-03           955            9      17  510.17
3  4 2019-01-03           577           19       3   68.49
4  5 2019-01-03           429            8      18  759.42

In [ ]:
merged_df = pd.merge(data, data_purchases, on='id', how='inner')
merged_df

,id,first_name,last_name,email,gender,street_num,street_name,street_suffix,city,state,postcode,full_name,purch_date,customer_num,product_num,amount,paid
0,1,Romain,Southcott,rsouthcott0@clickbank.net,Male,1.0,Trailsway,Road,San Diego,California,92127.0,Romain Southcott,2019-01-03,823,27,12,568.92
1,2,Cosimo,Molyneaux,cmolyneaux1@wiley.com,Male,NaN,NaN,NaN,El Paso,Texas,NaN,Cosimo Molyneaux,2019-01-03,606,28,14,395.36
2,3,Bambi,Westrip,bwestrip2@symantec.com,Female,4057.0,Arkansas,Circle,San Antonio,Texas,78220.0,Bambi Westrip,2019-01-03,955,9,17,510.17
3,4,Roarke,Pankettman,rpankettman3@wiley.com,Male,74.0,Debs,Point,Memphis,Tennessee,38150.0,Roarke Pankettman,2019-01-03,577,19,3,68.49
4,5,Mikaela,Althorpe,malthorpe4@51.la,NaN,NaN,2nd,Drive,NaN,NaN,83732.0,Mikaela Althorpe,2019-01-03,429,8,18,759.42
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,Merrili,Alman,malmanrn@cornell.edu,Female,0.0,Thompson,Way,Reading,Pennsylvania,19610.0,Merrili Alman,2019-06-04,198,20,7,609.35
996,997,Winonah,Heckle,whecklero@fc2.com,Female,701.0,Rowland,Hill,Indianapolis,Indiana,46278.0,Winonah Heckle,2019-06-04,96,27,14,663.74
997,998,Tobit,Birt,NaN,Male,2.0,Basil,Road,Waterbury,Connecticut,6721.0,Tobit Birt,2019-06-04,181,7,2,27.66
998,999,Issiah,Standbrooke,istandbrookerq@yellowpages.com,Male,NaN,Kenwood,Drive,Savannah,Georgia,31405.0,Issiah Standbrooke,2019-06-04,951,54,4,87.68
999,1000,Elmore,Malpas,NaN,Male,205.0,Farwell,Park,Atlanta,Georgia,30386.0,Elmore Malpas,2019-06-04,435,20,18,1143.90

In [ ]:
merged_df_right = pd.merge(data, data_purchases, on='id', how='right')
merged_df_right

,id,first_name,last_name,email,gender,street_num,street_name,street_suffix,city,state,postcode,full_name,purch_date,customer_num,product_num,amount,paid
0,1,Romain,Southcott,rsouthcott0@clickbank.net,Male,1.0,Trailsway,Road,San Diego,California,92127.0,Romain Southcott,2019-01-03,823,27,12,568.92
1,2,Cosimo,Molyneaux,cmolyneaux1@wiley.com,Male,NaN,NaN,NaN,El Paso,Texas,NaN,Cosimo Molyneaux,2019-01-03,606,28,14,395.36
2,3,Bambi,Westrip,bwestrip2@symantec.com,Female,4057.0,Arkansas,Circle,San Antonio,Texas,78220.0,Bambi Westrip,2019-01-03,955,9,17,510.17
3,4,Roarke,Pankettman,rpankettman3@wiley.com,Male,74.0,Debs,Point,Memphis,Tennessee,38150.0,Roarke Pankettman,2019-01-03,577,19,3,68.49
4,5,Mikaela,Althorpe,malthorpe4@51.la,NaN,NaN,2nd,Drive,NaN,NaN,83732.0,Mikaela Althorpe,2019-01-03,429,8,18,759.42
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5995,5996,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-06-20,893,33,5,411.10
5996,5997,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-06-20,566,23,11,178.97
5997,5998,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-06-20,114,19,9,205.47
5998,5999,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-06-20,404,11,20,429.40
5999,6000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-06-20,88,57,4,274.52

In [ ]:
data1_customers = pd.DataFrame({
    'id': [1, 2, 3],
    'name': ['alice', 'bob', 'charlie'],
    'product':['book', 'pen', 'notebook']
})


data2_purchases = pd.DataFrame({
    'id': [2, 3, 4],
    'product': ['pen', 'notebook', 'pen'],
    'amount' : [5, 10, 15]
})

merged_df = pd.merge(data1_customers, data2_purchases, on='id', how='left', suffixes=('_cust', '_pur'))
merged_df

   id     name product_cust product_pur  amount
0   1    alice         book         NaN     NaN
1   2      bob          pen         pen     5.0
2   3  charlie     notebook    notebook    10.0

Task 3: Difference between pd.concat, pd.merge and pd.join

Missing Values

In [ ]:
data.isnull().sum()

id                 0
first_name         0
last_name          0
email            122
gender            43
street_num       262
street_name       37
street_suffix     37
city              79
state             80
postcode         157
full_name          0
dtype: int64

In [ ]:
data_purchases.isnull().sum()

id              0
purch_date      0
customer_num    0
product_num     0
amount          0
paid            0
dtype: int64

In [ ]:
data_products.isnull().sum()

id         0
product    0
cost       0
company    5
dtype: int64

Drop all the missing values.

In [ ]:
customers_copy = data.copy()
customers_copy.head()

,id,first_name,last_name,email,gender,street_num,street_name,street_suffix,city,state,postcode,full_name
firstCustomer,1,Romain,Southcott,rsouthcott0@clickbank.net,Male,1.0,Trailsway,Road,San Diego,California,92127.0,Romain Southcott
secondCustomer,2,Cosimo,Molyneaux,cmolyneaux1@wiley.com,Male,NaN,NaN,NaN,El Paso,Texas,NaN,Cosimo Molyneaux
2,3,Bambi,Westrip,bwestrip2@symantec.com,Female,4057.0,Arkansas,Circle,San Antonio,Texas,78220.0,Bambi Westrip
3,4,Roarke,Pankettman,rpankettman3@wiley.com,Male,74.0,Debs,Point,Memphis,Tennessee,38150.0,Roarke Pankettman
4,5,Mikaela,Althorpe,malthorpe4@51.la,NaN,NaN,2nd,Drive,NaN,NaN,83732.0,Mikaela Althorpe

Strategy 1: dropna() -> only when you have a very small proportion of the missing data. Otherwise, please avoid this strategy because that leads to the loss of information.

In [ ]:
customers_copy = customers_copy.dropna()
customers_copy.isnull().sum()

id               0
first_name       0
last_name        0
email            0
gender           0
street_num       0
street_name      0
street_suffix    0
city             0
state            0
postcode         0
full_name        0
dtype: int64

In [ ]:
customers_copy.shape

(418, 12)

Strategy 2: Data Imputation

Imputation -> With the measures of central tendency [mean, median, mode]

How can we deal with the categorical data -> mode

Suppose i have 40% null data and remaining data have 50% male and 50% female and if use male to fill remaining null values as it is first occuring will that be an inaccuracy?

In [ ]:
mode_gender = data['gender'].mode()[0]
print(mode_gender)

Male

In [ ]:
data['gender'].fillna(mode_gender, inplace=True)
data.isnull().sum()

<ipython-input-48-1798c3f4fc8a>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['gender'].fillna(mode_gender, inplace=True)

id                 0
first_name         0
last_name          0
email            122
gender             0
street_num       262
street_name       37
street_suffix     37
city              79
state             80
postcode         157
full_name          0
dtype: int64

In [ ]:
data.shape

(1000, 12)

In [ ]:
data.head(20)

,id,first_name,last_name,email,gender,street_num,street_name,street_suffix,city,state,postcode,full_name
firstCustomer,1,Romain,Southcott,rsouthcott0@clickbank.net,Male,1.0,Trailsway,Road,San Diego,California,92127.0,Romain Southcott
secondCustomer,2,Cosimo,Molyneaux,cmolyneaux1@wiley.com,Male,NaN,NaN,NaN,El Paso,Texas,NaN,Cosimo Molyneaux
2,3,Bambi,Westrip,bwestrip2@symantec.com,Female,4057.0,Arkansas,Circle,San Antonio,Texas,78220.0,Bambi Westrip
3,4,Roarke,Pankettman,rpankettman3@wiley.com,Male,74.0,Debs,Point,Memphis,Tennessee,38150.0,Roarke Pankettman
4,5,Mikaela,Althorpe,malthorpe4@51.la,Male,NaN,2nd,Drive,NaN,NaN,83732.0,Mikaela Althorpe
5,6,Magdalena,Cullip,mcullip5@tiny.cc,Female,9190.0,Packers,Drive,Baltimore,Maryland,21229.0,Magdalena Cullip
6,7,Marietta,Heball,mheball6@blog.com,Female,12.0,Mallory,Center,Carol Stream,Illinois,60351.0,Marietta Heball
7,8,Tine,McSperrin,tmcsperrin7@statcounter.com,Male,530.0,Erie,Plaza,Kansas City,Missouri,64193.0,Tine McSperrin
8,9,Enrichetta,de Villier,edevillier8@ox.ac.uk,Female,745.0,Annamark,Street,Fairbanks,Alaska,99709.0,Enrichetta de Villier
9,10,Sari,Poulden,spoulden9@xing.com,Female,2.0,Pond,Hill,New Orleans,Louisiana,NaN,Sari Poulden
10,11,Natale,Martina,nmartinaa@wordpress.com,Male,221.0,Sauthoff,Pass,Bradenton,Florida,34205.0,Natale Martina
11,12,Noni,Norrington,nnorringtonb@netvibes.com,Female,5.0,NaN,NaN,Baltimore,Maryland,21282.0,Noni Norrington
12,13,Mikol,MacWhan,mmacwhanc@patch.com,Male,9.0,Eagle Crest,Center,Bronx,New York,10469.0,Mikol MacWhan
13,14,Deny,Thraves,dthravesd@ibm.com,Female,71865.0,Valley Edge,Place,Washington,District of Columbia,20456.0,Deny Thraves
14,15,Fara,Petegrew,fpetegrewe@ebay.com,Female,NaN,Claremont,Place,Los Angeles,California,90005.0,Fara Petegrew
15,16,Jodie,De Cristoforo,jdecristoforof@mac.com,Male,50948.0,Rowland,Alley,Charleston,South Carolina,29424.0,Jodie De Cristoforo
16,17,Tobi,Dewicke,tdewickeg@hostgator.com,Female,6817.0,Orin,Junction,San Rafael,NaN,NaN,Tobi Dewicke
17,18,Reinhold,Woolforde,rwoolfordeh@cbc.ca,Male,NaN,Northwestern,Way,Amarillo,Texas,79118.0,Reinhold Woolforde
18,19,Fredek,Foley,ffoleyi@bbb.org,Male,8.0,Ridgeway,Park,Silver Spring,Maryland,20910.0,Fredek Foley
19,20,Rubina,Hustings,rhustingsj@wikimedia.org,Female,249.0,Esker,Hill,San Antonio,Texas,78210.0,Rubina Hustings

How can we deal with the numeric data -> ffill(), bfill(), mean(), median()

In [ ]:
data.head(40)

,id,first_name,last_name,email,gender,street_num,street_name,street_suffix,city,state,postcode,full_name
firstCustomer,1,Romain,Southcott,rsouthcott0@clickbank.net,Male,1.0,Trailsway,Road,San Diego,California,92127.0,Romain Southcott
secondCustomer,2,Cosimo,Molyneaux,cmolyneaux1@wiley.com,Male,NaN,NaN,NaN,El Paso,Texas,NaN,Cosimo Molyneaux
2,3,Bambi,Westrip,bwestrip2@symantec.com,Female,4057.0,Arkansas,Circle,San Antonio,Texas,78220.0,Bambi Westrip
3,4,Roarke,Pankettman,rpankettman3@wiley.com,Male,74.0,Debs,Point,Memphis,Tennessee,38150.0,Roarke Pankettman
4,5,Mikaela,Althorpe,malthorpe4@51.la,Male,NaN,2nd,Drive,NaN,NaN,83732.0,Mikaela Althorpe
5,6,Magdalena,Cullip,mcullip5@tiny.cc,Female,9190.0,Packers,Drive,Baltimore,Maryland,21229.0,Magdalena Cullip
6,7,Marietta,Heball,mheball6@blog.com,Female,12.0,Mallory,Center,Carol Stream,Illinois,60351.0,Marietta Heball
7,8,Tine,McSperrin,tmcsperrin7@statcounter.com,Male,530.0,Erie,Plaza,Kansas City,Missouri,64193.0,Tine McSperrin
8,9,Enrichetta,de Villier,edevillier8@ox.ac.uk,Female,745.0,Annamark,Street,Fairbanks,Alaska,99709.0,Enrichetta de Villier
9,10,Sari,Poulden,spoulden9@xing.com,Female,2.0,Pond,Hill,New Orleans,Louisiana,NaN,Sari Poulden
10,11,Natale,Martina,nmartinaa@wordpress.com,Male,221.0,Sauthoff,Pass,Bradenton,Florida,34205.0,Natale Martina
11,12,Noni,Norrington,nnorringtonb@netvibes.com,Female,5.0,NaN,NaN,Baltimore,Maryland,21282.0,Noni Norrington
12,13,Mikol,MacWhan,mmacwhanc@patch.com,Male,9.0,Eagle Crest,Center,Bronx,New York,10469.0,Mikol MacWhan
13,14,Deny,Thraves,dthravesd@ibm.com,Female,71865.0,Valley Edge,Place,Washington,District of Columbia,20456.0,Deny Thraves
14,15,Fara,Petegrew,fpetegrewe@ebay.com,Female,NaN,Claremont,Place,Los Angeles,California,90005.0,Fara Petegrew
15,16,Jodie,De Cristoforo,jdecristoforof@mac.com,Male,50948.0,Rowland,Alley,Charleston,South Carolina,29424.0,Jodie De Cristoforo
16,17,Tobi,Dewicke,tdewickeg@hostgator.com,Female,6817.0,Orin,Junction,San Rafael,NaN,NaN,Tobi Dewicke
17,18,Reinhold,Woolforde,rwoolfordeh@cbc.ca,Male,NaN,Northwestern,Way,Amarillo,Texas,79118.0,Reinhold Woolforde
18,19,Fredek,Foley,ffoleyi@bbb.org,Male,8.0,Ridgeway,Park,Silver Spring,Maryland,20910.0,Fredek Foley
19,20,Rubina,Hustings,rhustingsj@wikimedia.org,Female,249.0,Esker,Hill,San Antonio,Texas,78210.0,Rubina Hustings
20,21,Karim,Woosnam,kwoosnamk@ifeng.com,Male,NaN,Grayhawk,Place,Houston,Texas,NaN,Karim Woosnam
21,22,Woodrow,Fidoe,wfidoel@creativecommons.org,Male,1.0,Artisan,Junction,Gainesville,NaN,NaN,Woodrow Fidoe
22,23,Loralie,Normand,lnormandm@usa.gov,Female,1.0,Transport,Terrace,Duluth,NaN,30195.0,Loralie Normand
23,24,Danita,Cleynaert,dcleynaertn@t-online.de,Female,NaN,Shopko,Center,Denton,Texas,76205.0,Danita Cleynaert
24,25,Tomlin,Massinger,NaN,Male,9.0,Victoria,Trail,Washington,District of Columbia,20409.0,Tomlin Massinger
25,26,Franklin,Goodge,fgoodgep@mapquest.com,Male,97670.0,Kensington,Center,Houston,Texas,77240.0,Franklin Goodge
26,27,Harlene,Rameau,hrameauq@squarespace.com,Female,2352.0,American,Way,Seattle,Washington,98127.0,Harlene Rameau
27,28,Brander,Quinnelly,bquinnellyr@shinystat.com,Male,573.0,Dovetail,Center,Sparks,Nevada,89436.0,Brander Quinnelly
28,29,Jeanna,Bruntje,jbruntjes@tuttocitta.it,Female,9296.0,Hanover,Road,Fort Wayne,Indiana,46814.0,Jeanna Bruntje
29,30,Ardyth,Zack,azackt@wordpress.com,Female,437.0,Pierstorff,Way,Pittsburgh,Pennsylvania,NaN,Ardyth Zack
30,31,Steve,Pantridge,NaN,Male,6124.0,Kropf,Street,Los Angeles,California,90065.0,Steve Pantridge
31,32,Brit,Nouch,bnouchv@yahoo.com,Female,2385.0,Blaine,Trail,Augusta,Georgia,NaN,Brit Nouch
32,33,Caril,Barnsley,cbarnsleyw@bravesites.com,Female,NaN,Mallory,Way,Fort Wayne,Indiana,46896.0,Caril Barnsley
33,34,Rosalynd,Dyerson,rdyersonx@geocities.jp,Female,NaN,Cody,Court,Dallas,Texas,75226.0,Rosalynd Dyerson
34,35,Griffy,Sonley,gsonleyy@deviantart.com,Male,1.0,NaN,NaN,NaN,Virginia,22070.0,Griffy Sonley
35,36,Ernest,Armal,earmalz@dailymail.co.uk,Male,4.0,Susan,Center,Washington,District of Columbia,20231.0,Ernest Armal
36,37,Elspeth,Mendus,emendus10@ocn.ne.jp,Female,127.0,Mockingbird,Hill,Washington,District of Columbia,NaN,Elspeth Mendus
37,38,Clarita,Bussons,cbussons11@marketwatch.com,Female,7444.0,Northwestern,Crossing,Lansing,Michigan,48912.0,Clarita Bussons
38,39,Stanislas,Hacaud,NaN,Male,76.0,Summer Ridge,Place,Atlanta,Georgia,31119.0,Stanislas Hacaud
39,40,Melvyn,Seifert,mseifert13@photobucket.com,Male,NaN,Park Meadow,Pass,San Antonio,Texas,78260.0,Melvyn Seifert

In [ ]:
data['street_num'].fillna(method='ffill', inplace=True)
data.isnull().sum()

<ipython-input-52-c4ae133be938>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['street_num'].fillna(method='ffill', inplace=True)
<ipython-input-52-c4ae133be938>:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data['street_num'].fillna(method='ffill', inplace=True)

id                 0
first_name         0
last_name          0
email            122
gender             0
street_num         0
street_name       37
street_suffix     37
city              79
state             80
postcode         157
full_name          0
dtype: int64

In [ ]:
data.head(40)

,id,first_name,last_name,email,gender,street_num,street_name,street_suffix,city,state,postcode,full_name
firstCustomer,1,Romain,Southcott,rsouthcott0@clickbank.net,Male,1.0,Trailsway,Road,San Diego,California,92127.0,Romain Southcott
secondCustomer,2,Cosimo,Molyneaux,cmolyneaux1@wiley.com,Male,1.0,NaN,NaN,El Paso,Texas,NaN,Cosimo Molyneaux
2,3,Bambi,Westrip,bwestrip2@symantec.com,Female,4057.0,Arkansas,Circle,San Antonio,Texas,78220.0,Bambi Westrip
3,4,Roarke,Pankettman,rpankettman3@wiley.com,Male,74.0,Debs,Point,Memphis,Tennessee,38150.0,Roarke Pankettman
4,5,Mikaela,Althorpe,malthorpe4@51.la,Male,74.0,2nd,Drive,NaN,NaN,83732.0,Mikaela Althorpe
5,6,Magdalena,Cullip,mcullip5@tiny.cc,Female,9190.0,Packers,Drive,Baltimore,Maryland,21229.0,Magdalena Cullip
6,7,Marietta,Heball,mheball6@blog.com,Female,12.0,Mallory,Center,Carol Stream,Illinois,60351.0,Marietta Heball
7,8,Tine,McSperrin,tmcsperrin7@statcounter.com,Male,530.0,Erie,Plaza,Kansas City,Missouri,64193.0,Tine McSperrin
8,9,Enrichetta,de Villier,edevillier8@ox.ac.uk,Female,745.0,Annamark,Street,Fairbanks,Alaska,99709.0,Enrichetta de Villier
9,10,Sari,Poulden,spoulden9@xing.com,Female,2.0,Pond,Hill,New Orleans,Louisiana,NaN,Sari Poulden
10,11,Natale,Martina,nmartinaa@wordpress.com,Male,221.0,Sauthoff,Pass,Bradenton,Florida,34205.0,Natale Martina
11,12,Noni,Norrington,nnorringtonb@netvibes.com,Female,5.0,NaN,NaN,Baltimore,Maryland,21282.0,Noni Norrington
12,13,Mikol,MacWhan,mmacwhanc@patch.com,Male,9.0,Eagle Crest,Center,Bronx,New York,10469.0,Mikol MacWhan
13,14,Deny,Thraves,dthravesd@ibm.com,Female,71865.0,Valley Edge,Place,Washington,District of Columbia,20456.0,Deny Thraves
14,15,Fara,Petegrew,fpetegrewe@ebay.com,Female,71865.0,Claremont,Place,Los Angeles,California,90005.0,Fara Petegrew
15,16,Jodie,De Cristoforo,jdecristoforof@mac.com,Male,50948.0,Rowland,Alley,Charleston,South Carolina,29424.0,Jodie De Cristoforo
16,17,Tobi,Dewicke,tdewickeg@hostgator.com,Female,6817.0,Orin,Junction,San Rafael,NaN,NaN,Tobi Dewicke
17,18,Reinhold,Woolforde,rwoolfordeh@cbc.ca,Male,6817.0,Northwestern,Way,Amarillo,Texas,79118.0,Reinhold Woolforde
18,19,Fredek,Foley,ffoleyi@bbb.org,Male,8.0,Ridgeway,Park,Silver Spring,Maryland,20910.0,Fredek Foley
19,20,Rubina,Hustings,rhustingsj@wikimedia.org,Female,249.0,Esker,Hill,San Antonio,Texas,78210.0,Rubina Hustings
20,21,Karim,Woosnam,kwoosnamk@ifeng.com,Male,249.0,Grayhawk,Place,Houston,Texas,NaN,Karim Woosnam
21,22,Woodrow,Fidoe,wfidoel@creativecommons.org,Male,1.0,Artisan,Junction,Gainesville,NaN,NaN,Woodrow Fidoe
22,23,Loralie,Normand,lnormandm@usa.gov,Female,1.0,Transport,Terrace,Duluth,NaN,30195.0,Loralie Normand
23,24,Danita,Cleynaert,dcleynaertn@t-online.de,Female,1.0,Shopko,Center,Denton,Texas,76205.0,Danita Cleynaert
24,25,Tomlin,Massinger,NaN,Male,9.0,Victoria,Trail,Washington,District of Columbia,20409.0,Tomlin Massinger
25,26,Franklin,Goodge,fgoodgep@mapquest.com,Male,97670.0,Kensington,Center,Houston,Texas,77240.0,Franklin Goodge
26,27,Harlene,Rameau,hrameauq@squarespace.com,Female,2352.0,American,Way,Seattle,Washington,98127.0,Harlene Rameau
27,28,Brander,Quinnelly,bquinnellyr@shinystat.com,Male,573.0,Dovetail,Center,Sparks,Nevada,89436.0,Brander Quinnelly
28,29,Jeanna,Bruntje,jbruntjes@tuttocitta.it,Female,9296.0,Hanover,Road,Fort Wayne,Indiana,46814.0,Jeanna Bruntje
29,30,Ardyth,Zack,azackt@wordpress.com,Female,437.0,Pierstorff,Way,Pittsburgh,Pennsylvania,NaN,Ardyth Zack
30,31,Steve,Pantridge,NaN,Male,6124.0,Kropf,Street,Los Angeles,California,90065.0,Steve Pantridge
31,32,Brit,Nouch,bnouchv@yahoo.com,Female,2385.0,Blaine,Trail,Augusta,Georgia,NaN,Brit Nouch
32,33,Caril,Barnsley,cbarnsleyw@bravesites.com,Female,2385.0,Mallory,Way,Fort Wayne,Indiana,46896.0,Caril Barnsley
33,34,Rosalynd,Dyerson,rdyersonx@geocities.jp,Female,2385.0,Cody,Court,Dallas,Texas,75226.0,Rosalynd Dyerson
34,35,Griffy,Sonley,gsonleyy@deviantart.com,Male,1.0,NaN,NaN,NaN,Virginia,22070.0,Griffy Sonley
35,36,Ernest,Armal,earmalz@dailymail.co.uk,Male,4.0,Susan,Center,Washington,District of Columbia,20231.0,Ernest Armal
36,37,Elspeth,Mendus,emendus10@ocn.ne.jp,Female,127.0,Mockingbird,Hill,Washington,District of Columbia,NaN,Elspeth Mendus
37,38,Clarita,Bussons,cbussons11@marketwatch.com,Female,7444.0,Northwestern,Crossing,Lansing,Michigan,48912.0,Clarita Bussons
38,39,Stanislas,Hacaud,NaN,Male,76.0,Summer Ridge,Place,Atlanta,Georgia,31119.0,Stanislas Hacaud
39,40,Melvyn,Seifert,mseifert13@photobucket.com,Male,76.0,Park Meadow,Pass,San Antonio,Texas,78260.0,Melvyn Seifert

Can you apply the similar strategy of ffill() in the street_name and street_suffix column as well.

In [ ]:
data['street_name'].fillna(method='ffill', inplace=True)
data['street_suffix'].fillna(method='ffill', inplace=True)

<ipython-input-54-7a50f339a9c1>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['street_name'].fillna(method='ffill', inplace=True)
<ipython-input-54-7a50f339a9c1>:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data['street_name'].fillna(method='ffill', inplace=True)
<ipython-input-54-7a50f339a9c1>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['street_suffix'].fillna(method='ffill', inplace=True)
<ipython-input-54-7a50f339a9c1>:2: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data['street_suffix'].fillna(method='ffill', inplace=True)

In [ ]:
data.isnull().sum()

id                 0
first_name         0
last_name          0
email            122
gender             0
street_num         0
street_name        0
street_suffix      0
city              79
state             80
postcode         157
full_name          0
dtype: int64

In [ ]:
data.head(40)

,id,first_name,last_name,email,gender,street_num,street_name,street_suffix,city,state,postcode,full_name
firstCustomer,1,Romain,Southcott,rsouthcott0@clickbank.net,Male,1.0,Trailsway,Road,San Diego,California,92127.0,Romain Southcott
secondCustomer,2,Cosimo,Molyneaux,cmolyneaux1@wiley.com,Male,1.0,Trailsway,Road,El Paso,Texas,NaN,Cosimo Molyneaux
2,3,Bambi,Westrip,bwestrip2@symantec.com,Female,4057.0,Arkansas,Circle,San Antonio,Texas,78220.0,Bambi Westrip
3,4,Roarke,Pankettman,rpankettman3@wiley.com,Male,74.0,Debs,Point,Memphis,Tennessee,38150.0,Roarke Pankettman
4,5,Mikaela,Althorpe,malthorpe4@51.la,Male,74.0,2nd,Drive,NaN,NaN,83732.0,Mikaela Althorpe
5,6,Magdalena,Cullip,mcullip5@tiny.cc,Female,9190.0,Packers,Drive,Baltimore,Maryland,21229.0,Magdalena Cullip
6,7,Marietta,Heball,mheball6@blog.com,Female,12.0,Mallory,Center,Carol Stream,Illinois,60351.0,Marietta Heball
7,8,Tine,McSperrin,tmcsperrin7@statcounter.com,Male,530.0,Erie,Plaza,Kansas City,Missouri,64193.0,Tine McSperrin
8,9,Enrichetta,de Villier,edevillier8@ox.ac.uk,Female,745.0,Annamark,Street,Fairbanks,Alaska,99709.0,Enrichetta de Villier
9,10,Sari,Poulden,spoulden9@xing.com,Female,2.0,Pond,Hill,New Orleans,Louisiana,NaN,Sari Poulden
10,11,Natale,Martina,nmartinaa@wordpress.com,Male,221.0,Sauthoff,Pass,Bradenton,Florida,34205.0,Natale Martina
11,12,Noni,Norrington,nnorringtonb@netvibes.com,Female,5.0,Sauthoff,Pass,Baltimore,Maryland,21282.0,Noni Norrington
12,13,Mikol,MacWhan,mmacwhanc@patch.com,Male,9.0,Eagle Crest,Center,Bronx,New York,10469.0,Mikol MacWhan
13,14,Deny,Thraves,dthravesd@ibm.com,Female,71865.0,Valley Edge,Place,Washington,District of Columbia,20456.0,Deny Thraves
14,15,Fara,Petegrew,fpetegrewe@ebay.com,Female,71865.0,Claremont,Place,Los Angeles,California,90005.0,Fara Petegrew
15,16,Jodie,De Cristoforo,jdecristoforof@mac.com,Male,50948.0,Rowland,Alley,Charleston,South Carolina,29424.0,Jodie De Cristoforo
16,17,Tobi,Dewicke,tdewickeg@hostgator.com,Female,6817.0,Orin,Junction,San Rafael,NaN,NaN,Tobi Dewicke
17,18,Reinhold,Woolforde,rwoolfordeh@cbc.ca,Male,6817.0,Northwestern,Way,Amarillo,Texas,79118.0,Reinhold Woolforde
18,19,Fredek,Foley,ffoleyi@bbb.org,Male,8.0,Ridgeway,Park,Silver Spring,Maryland,20910.0,Fredek Foley
19,20,Rubina,Hustings,rhustingsj@wikimedia.org,Female,249.0,Esker,Hill,San Antonio,Texas,78210.0,Rubina Hustings
20,21,Karim,Woosnam,kwoosnamk@ifeng.com,Male,249.0,Grayhawk,Place,Houston,Texas,NaN,Karim Woosnam
21,22,Woodrow,Fidoe,wfidoel@creativecommons.org,Male,1.0,Artisan,Junction,Gainesville,NaN,NaN,Woodrow Fidoe
22,23,Loralie,Normand,lnormandm@usa.gov,Female,1.0,Transport,Terrace,Duluth,NaN,30195.0,Loralie Normand
23,24,Danita,Cleynaert,dcleynaertn@t-online.de,Female,1.0,Shopko,Center,Denton,Texas,76205.0,Danita Cleynaert
24,25,Tomlin,Massinger,NaN,Male,9.0,Victoria,Trail,Washington,District of Columbia,20409.0,Tomlin Massinger
25,26,Franklin,Goodge,fgoodgep@mapquest.com,Male,97670.0,Kensington,Center,Houston,Texas,77240.0,Franklin Goodge
26,27,Harlene,Rameau,hrameauq@squarespace.com,Female,2352.0,American,Way,Seattle,Washington,98127.0,Harlene Rameau
27,28,Brander,Quinnelly,bquinnellyr@shinystat.com,Male,573.0,Dovetail,Center,Sparks,Nevada,89436.0,Brander Quinnelly
28,29,Jeanna,Bruntje,jbruntjes@tuttocitta.it,Female,9296.0,Hanover,Road,Fort Wayne,Indiana,46814.0,Jeanna Bruntje
29,30,Ardyth,Zack,azackt@wordpress.com,Female,437.0,Pierstorff,Way,Pittsburgh,Pennsylvania,NaN,Ardyth Zack
30,31,Steve,Pantridge,NaN,Male,6124.0,Kropf,Street,Los Angeles,California,90065.0,Steve Pantridge
31,32,Brit,Nouch,bnouchv@yahoo.com,Female,2385.0,Blaine,Trail,Augusta,Georgia,NaN,Brit Nouch
32,33,Caril,Barnsley,cbarnsleyw@bravesites.com,Female,2385.0,Mallory,Way,Fort Wayne,Indiana,46896.0,Caril Barnsley
33,34,Rosalynd,Dyerson,rdyersonx@geocities.jp,Female,2385.0,Cody,Court,Dallas,Texas,75226.0,Rosalynd Dyerson
34,35,Griffy,Sonley,gsonleyy@deviantart.com,Male,1.0,Cody,Court,NaN,Virginia,22070.0,Griffy Sonley
35,36,Ernest,Armal,earmalz@dailymail.co.uk,Male,4.0,Susan,Center,Washington,District of Columbia,20231.0,Ernest Armal
36,37,Elspeth,Mendus,emendus10@ocn.ne.jp,Female,127.0,Mockingbird,Hill,Washington,District of Columbia,NaN,Elspeth Mendus
37,38,Clarita,Bussons,cbussons11@marketwatch.com,Female,7444.0,Northwestern,Crossing,Lansing,Michigan,48912.0,Clarita Bussons
38,39,Stanislas,Hacaud,NaN,Male,76.0,Summer Ridge,Place,Atlanta,Georgia,31119.0,Stanislas Hacaud
39,40,Melvyn,Seifert,mseifert13@photobucket.com,Male,76.0,Park Meadow,Pass,San Antonio,Texas,78260.0,Melvyn Seifert

In [ ]:
data['city'].fillna(method='bfill', inplace=True)
data['state'].fillna(method='bfill', inplace=True)
data['postcode'].fillna(method='bfill', inplace=True)

data.head(40)

<ipython-input-57-ecb511bb17bc>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['city'].fillna(method='bfill', inplace=True)
<ipython-input-57-ecb511bb17bc>:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data['city'].fillna(method='bfill', inplace=True)
<ipython-input-57-ecb511bb17bc>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['state'].fillna(method='bfill', inplace=True)
<ipython-input-57-ecb511bb17bc>:2: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data['state'].fillna(method='bfill', inplace=True)
<ipython-input-57-ecb511bb17bc>:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['postcode'].fillna(method='bfill', inplace=True)
<ipython-input-57-ecb511bb17bc>:3: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data['postcode'].fillna(method='bfill', inplace=True)

,id,first_name,last_name,email,gender,street_num,street_name,street_suffix,city,state,postcode,full_name
firstCustomer,1,Romain,Southcott,rsouthcott0@clickbank.net,Male,1.0,Trailsway,Road,San Diego,California,92127.0,Romain Southcott
secondCustomer,2,Cosimo,Molyneaux,cmolyneaux1@wiley.com,Male,1.0,Trailsway,Road,El Paso,Texas,78220.0,Cosimo Molyneaux
2,3,Bambi,Westrip,bwestrip2@symantec.com,Female,4057.0,Arkansas,Circle,San Antonio,Texas,78220.0,Bambi Westrip
3,4,Roarke,Pankettman,rpankettman3@wiley.com,Male,74.0,Debs,Point,Memphis,Tennessee,38150.0,Roarke Pankettman
4,5,Mikaela,Althorpe,malthorpe4@51.la,Male,74.0,2nd,Drive,Baltimore,Maryland,83732.0,Mikaela Althorpe
5,6,Magdalena,Cullip,mcullip5@tiny.cc,Female,9190.0,Packers,Drive,Baltimore,Maryland,21229.0,Magdalena Cullip
6,7,Marietta,Heball,mheball6@blog.com,Female,12.0,Mallory,Center,Carol Stream,Illinois,60351.0,Marietta Heball
7,8,Tine,McSperrin,tmcsperrin7@statcounter.com,Male,530.0,Erie,Plaza,Kansas City,Missouri,64193.0,Tine McSperrin
8,9,Enrichetta,de Villier,edevillier8@ox.ac.uk,Female,745.0,Annamark,Street,Fairbanks,Alaska,99709.0,Enrichetta de Villier
9,10,Sari,Poulden,spoulden9@xing.com,Female,2.0,Pond,Hill,New Orleans,Louisiana,34205.0,Sari Poulden
10,11,Natale,Martina,nmartinaa@wordpress.com,Male,221.0,Sauthoff,Pass,Bradenton,Florida,34205.0,Natale Martina
11,12,Noni,Norrington,nnorringtonb@netvibes.com,Female,5.0,Sauthoff,Pass,Baltimore,Maryland,21282.0,Noni Norrington
12,13,Mikol,MacWhan,mmacwhanc@patch.com,Male,9.0,Eagle Crest,Center,Bronx,New York,10469.0,Mikol MacWhan
13,14,Deny,Thraves,dthravesd@ibm.com,Female,71865.0,Valley Edge,Place,Washington,District of Columbia,20456.0,Deny Thraves
14,15,Fara,Petegrew,fpetegrewe@ebay.com,Female,71865.0,Claremont,Place,Los Angeles,California,90005.0,Fara Petegrew
15,16,Jodie,De Cristoforo,jdecristoforof@mac.com,Male,50948.0,Rowland,Alley,Charleston,South Carolina,29424.0,Jodie De Cristoforo
16,17,Tobi,Dewicke,tdewickeg@hostgator.com,Female,6817.0,Orin,Junction,San Rafael,Texas,79118.0,Tobi Dewicke
17,18,Reinhold,Woolforde,rwoolfordeh@cbc.ca,Male,6817.0,Northwestern,Way,Amarillo,Texas,79118.0,Reinhold Woolforde
18,19,Fredek,Foley,ffoleyi@bbb.org,Male,8.0,Ridgeway,Park,Silver Spring,Maryland,20910.0,Fredek Foley
19,20,Rubina,Hustings,rhustingsj@wikimedia.org,Female,249.0,Esker,Hill,San Antonio,Texas,78210.0,Rubina Hustings
20,21,Karim,Woosnam,kwoosnamk@ifeng.com,Male,249.0,Grayhawk,Place,Houston,Texas,30195.0,Karim Woosnam
21,22,Woodrow,Fidoe,wfidoel@creativecommons.org,Male,1.0,Artisan,Junction,Gainesville,Texas,30195.0,Woodrow Fidoe
22,23,Loralie,Normand,lnormandm@usa.gov,Female,1.0,Transport,Terrace,Duluth,Texas,30195.0,Loralie Normand
23,24,Danita,Cleynaert,dcleynaertn@t-online.de,Female,1.0,Shopko,Center,Denton,Texas,76205.0,Danita Cleynaert
24,25,Tomlin,Massinger,NaN,Male,9.0,Victoria,Trail,Washington,District of Columbia,20409.0,Tomlin Massinger
25,26,Franklin,Goodge,fgoodgep@mapquest.com,Male,97670.0,Kensington,Center,Houston,Texas,77240.0,Franklin Goodge
26,27,Harlene,Rameau,hrameauq@squarespace.com,Female,2352.0,American,Way,Seattle,Washington,98127.0,Harlene Rameau
27,28,Brander,Quinnelly,bquinnellyr@shinystat.com,Male,573.0,Dovetail,Center,Sparks,Nevada,89436.0,Brander Quinnelly
28,29,Jeanna,Bruntje,jbruntjes@tuttocitta.it,Female,9296.0,Hanover,Road,Fort Wayne,Indiana,46814.0,Jeanna Bruntje
29,30,Ardyth,Zack,azackt@wordpress.com,Female,437.0,Pierstorff,Way,Pittsburgh,Pennsylvania,90065.0,Ardyth Zack
30,31,Steve,Pantridge,NaN,Male,6124.0,Kropf,Street,Los Angeles,California,90065.0,Steve Pantridge
31,32,Brit,Nouch,bnouchv@yahoo.com,Female,2385.0,Blaine,Trail,Augusta,Georgia,46896.0,Brit Nouch
32,33,Caril,Barnsley,cbarnsleyw@bravesites.com,Female,2385.0,Mallory,Way,Fort Wayne,Indiana,46896.0,Caril Barnsley
33,34,Rosalynd,Dyerson,rdyersonx@geocities.jp,Female,2385.0,Cody,Court,Dallas,Texas,75226.0,Rosalynd Dyerson
34,35,Griffy,Sonley,gsonleyy@deviantart.com,Male,1.0,Cody,Court,Washington,Virginia,22070.0,Griffy Sonley
35,36,Ernest,Armal,earmalz@dailymail.co.uk,Male,4.0,Susan,Center,Washington,District of Columbia,20231.0,Ernest Armal
36,37,Elspeth,Mendus,emendus10@ocn.ne.jp,Female,127.0,Mockingbird,Hill,Washington,District of Columbia,48912.0,Elspeth Mendus
37,38,Clarita,Bussons,cbussons11@marketwatch.com,Female,7444.0,Northwestern,Crossing,Lansing,Michigan,48912.0,Clarita Bussons
38,39,Stanislas,Hacaud,NaN,Male,76.0,Summer Ridge,Place,Atlanta,Georgia,31119.0,Stanislas Hacaud
39,40,Melvyn,Seifert,mseifert13@photobucket.com,Male,76.0,Park Meadow,Pass,San Antonio,Texas,78260.0,Melvyn Seifert

In [ ]:
data.isnull().sum()

id                 0
first_name         0
last_name          0
email            122
gender             0
street_num         0
street_name        0
street_suffix      0
city               0
state              0
postcode           0
full_name          0
dtype: int64

In [ ]:
data['email'].fillna('Unknown', inplace=True)
data.head(40)

<ipython-input-59-62b6115176ef>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['email'].fillna('Unknown', inplace=True)

,id,first_name,last_name,email,gender,street_num,street_name,street_suffix,city,state,postcode,full_name
firstCustomer,1,Romain,Southcott,rsouthcott0@clickbank.net,Male,1.0,Trailsway,Road,San Diego,California,92127.0,Romain Southcott
secondCustomer,2,Cosimo,Molyneaux,cmolyneaux1@wiley.com,Male,1.0,Trailsway,Road,El Paso,Texas,78220.0,Cosimo Molyneaux
2,3,Bambi,Westrip,bwestrip2@symantec.com,Female,4057.0,Arkansas,Circle,San Antonio,Texas,78220.0,Bambi Westrip
3,4,Roarke,Pankettman,rpankettman3@wiley.com,Male,74.0,Debs,Point,Memphis,Tennessee,38150.0,Roarke Pankettman
4,5,Mikaela,Althorpe,malthorpe4@51.la,Male,74.0,2nd,Drive,Baltimore,Maryland,83732.0,Mikaela Althorpe
5,6,Magdalena,Cullip,mcullip5@tiny.cc,Female,9190.0,Packers,Drive,Baltimore,Maryland,21229.0,Magdalena Cullip
6,7,Marietta,Heball,mheball6@blog.com,Female,12.0,Mallory,Center,Carol Stream,Illinois,60351.0,Marietta Heball
7,8,Tine,McSperrin,tmcsperrin7@statcounter.com,Male,530.0,Erie,Plaza,Kansas City,Missouri,64193.0,Tine McSperrin
8,9,Enrichetta,de Villier,edevillier8@ox.ac.uk,Female,745.0,Annamark,Street,Fairbanks,Alaska,99709.0,Enrichetta de Villier
9,10,Sari,Poulden,spoulden9@xing.com,Female,2.0,Pond,Hill,New Orleans,Louisiana,34205.0,Sari Poulden
10,11,Natale,Martina,nmartinaa@wordpress.com,Male,221.0,Sauthoff,Pass,Bradenton,Florida,34205.0,Natale Martina
11,12,Noni,Norrington,nnorringtonb@netvibes.com,Female,5.0,Sauthoff,Pass,Baltimore,Maryland,21282.0,Noni Norrington
12,13,Mikol,MacWhan,mmacwhanc@patch.com,Male,9.0,Eagle Crest,Center,Bronx,New York,10469.0,Mikol MacWhan
13,14,Deny,Thraves,dthravesd@ibm.com,Female,71865.0,Valley Edge,Place,Washington,District of Columbia,20456.0,Deny Thraves
14,15,Fara,Petegrew,fpetegrewe@ebay.com,Female,71865.0,Claremont,Place,Los Angeles,California,90005.0,Fara Petegrew
15,16,Jodie,De Cristoforo,jdecristoforof@mac.com,Male,50948.0,Rowland,Alley,Charleston,South Carolina,29424.0,Jodie De Cristoforo
16,17,Tobi,Dewicke,tdewickeg@hostgator.com,Female,6817.0,Orin,Junction,San Rafael,Texas,79118.0,Tobi Dewicke
17,18,Reinhold,Woolforde,rwoolfordeh@cbc.ca,Male,6817.0,Northwestern,Way,Amarillo,Texas,79118.0,Reinhold Woolforde
18,19,Fredek,Foley,ffoleyi@bbb.org,Male,8.0,Ridgeway,Park,Silver Spring,Maryland,20910.0,Fredek Foley
19,20,Rubina,Hustings,rhustingsj@wikimedia.org,Female,249.0,Esker,Hill,San Antonio,Texas,78210.0,Rubina Hustings
20,21,Karim,Woosnam,kwoosnamk@ifeng.com,Male,249.0,Grayhawk,Place,Houston,Texas,30195.0,Karim Woosnam
21,22,Woodrow,Fidoe,wfidoel@creativecommons.org,Male,1.0,Artisan,Junction,Gainesville,Texas,30195.0,Woodrow Fidoe
22,23,Loralie,Normand,lnormandm@usa.gov,Female,1.0,Transport,Terrace,Duluth,Texas,30195.0,Loralie Normand
23,24,Danita,Cleynaert,dcleynaertn@t-online.de,Female,1.0,Shopko,Center,Denton,Texas,76205.0,Danita Cleynaert
24,25,Tomlin,Massinger,Unknown,Male,9.0,Victoria,Trail,Washington,District of Columbia,20409.0,Tomlin Massinger
25,26,Franklin,Goodge,fgoodgep@mapquest.com,Male,97670.0,Kensington,Center,Houston,Texas,77240.0,Franklin Goodge
26,27,Harlene,Rameau,hrameauq@squarespace.com,Female,2352.0,American,Way,Seattle,Washington,98127.0,Harlene Rameau
27,28,Brander,Quinnelly,bquinnellyr@shinystat.com,Male,573.0,Dovetail,Center,Sparks,Nevada,89436.0,Brander Quinnelly
28,29,Jeanna,Bruntje,jbruntjes@tuttocitta.it,Female,9296.0,Hanover,Road,Fort Wayne,Indiana,46814.0,Jeanna Bruntje
29,30,Ardyth,Zack,azackt@wordpress.com,Female,437.0,Pierstorff,Way,Pittsburgh,Pennsylvania,90065.0,Ardyth Zack
30,31,Steve,Pantridge,Unknown,Male,6124.0,Kropf,Street,Los Angeles,California,90065.0,Steve Pantridge
31,32,Brit,Nouch,bnouchv@yahoo.com,Female,2385.0,Blaine,Trail,Augusta,Georgia,46896.0,Brit Nouch
32,33,Caril,Barnsley,cbarnsleyw@bravesites.com,Female,2385.0,Mallory,Way,Fort Wayne,Indiana,46896.0,Caril Barnsley
33,34,Rosalynd,Dyerson,rdyersonx@geocities.jp,Female,2385.0,Cody,Court,Dallas,Texas,75226.0,Rosalynd Dyerson
34,35,Griffy,Sonley,gsonleyy@deviantart.com,Male,1.0,Cody,Court,Washington,Virginia,22070.0,Griffy Sonley
35,36,Ernest,Armal,earmalz@dailymail.co.uk,Male,4.0,Susan,Center,Washington,District of Columbia,20231.0,Ernest Armal
36,37,Elspeth,Mendus,emendus10@ocn.ne.jp,Female,127.0,Mockingbird,Hill,Washington,District of Columbia,48912.0,Elspeth Mendus
37,38,Clarita,Bussons,cbussons11@marketwatch.com,Female,7444.0,Northwestern,Crossing,Lansing,Michigan,48912.0,Clarita Bussons
38,39,Stanislas,Hacaud,Unknown,Male,76.0,Summer Ridge,Place,Atlanta,Georgia,31119.0,Stanislas Hacaud
39,40,Melvyn,Seifert,mseifert13@photobucket.com,Male,76.0,Park Meadow,Pass,San Antonio,Texas,78260.0,Melvyn Seifert

In [ ]:
data_products.isnull().sum()

id         0
product    0
cost       0
company    5
dtype: int64

Can you impute the missing values of the company with the 'Unknown'

In [ ]:
data_products['company'].fillna('Unknown', inplace=True)
data_products.isnull().sum()

<ipython-input-61-c2b19ed25efb>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data_products['company'].fillna('Unknown', inplace=True)

id         0
product    0
cost       0
company    0
dtype: int64

In [ ]:
data.isnull().sum()

id               0
first_name       0
last_name        0
email            0
gender           0
street_num       0
street_name      0
street_suffix    0
city             0
state            0
postcode         0
full_name        0
dtype: int64

In [ ]:
data_purchases.isnull().sum()

id              0
purch_date      0
customer_num    0
product_num     0
amount          0
paid            0
dtype: int64

In [ ]:
data.to_excel('customers.xlsx')
data_purchases.to_excel('purchases.xlsx')
data_products.to_excel('products.xlsx')

Data Analysis: Aggregation

Group by 'customer_num' and compute the sum of 'amount' and 'paid' column

In [ ]:
data_purchases.head(10)

   id purch_date  customer_num  product_num  amount     paid
0   1 2019-01-03           823           27      12   568.92
1   2 2019-01-03           606           28      14   395.36
2   3 2019-01-03           955            9      17   510.17
3   4 2019-01-03           577           19       3    68.49
4   5 2019-01-03           429            8      18   759.42
5   6 2019-01-03           275           36      18   176.76
6   7 2019-01-03           456           21      10   904.80
7   8 2019-01-03           526           58      19  1387.95
8   9 2019-01-03           326           44       2    61.34
9  10 2019-01-03            13           21       5   316.70

In [ ]:
aggregated_purchase = data_purchases.groupby('customer_num').agg({'amount':'sum', 'paid': 'sum'})
print(aggregated_purchase)

              amount     paid
customer_num
1                 24   779.34
2                 67  3978.09
3                 88  5031.39
4                 38  2276.38
5                 46  2931.24
...              ...      ...
996               31  2339.19
997               55  3030.34
998               69  3346.93
999               66  3640.48
1000              75  3961.63

[997 rows x 2 columns]

Can you give me the total amount and total paid as per the purchase_date.

In [ ]:
aggregated_purchase_date = data_purchases.groupby('purch_date').agg({'amount':'sum', 'paid':'sum'})
aggregated_purchase_date

            amount      paid
purch_date
2019-01-03     480  20468.33
2019-01-04     872  48529.13
2019-01-05     715  38643.67
2019-01-06     576  32345.29
2019-02-03     568  28183.50
...            ...       ...
2019-11-06     475  24778.05
2019-12-03     524  27691.62
2019-12-04     647  37100.59
2019-12-05     380  20845.55
2019-12-06     481  26410.08

[108 rows x 2 columns]

Task: Please explore the method drop_duplicates